config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'projects#index'
  devise_for :users, controllers: { invitations: 'users/invitations' }
  resources :users, only: %i[index show new create destroy update]
  resources :organisations, only: %i[index new create destroy]
  resources :sites, only: %i[show new create destroy] do
    get '/checks', to: 'sites#checks'
  end
  resources :projects, only: %i[index new create destroy]
  resources :slack_settings, only: %i[show new create update edit destroy]
  get '/probes', to: 'probes#index'
  post '/probes', to: 'probes#create'
  get '/probes/health/:id', to: 'probes#health'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/slack_setting.rb
# frozen_string_literal: true

class SlackSetting < ApplicationRecord
  belongs_to :project
  validates :webhook_url, :project_id, presence: true
end

app/controllers/slack_settings_controller.rb
# frozen_string_literal: true

class SlackSettingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_slack_setting, only: %i[show edit update destroy]

  # GET /slack_settings/1
  # GET /slack_settings/1.json
  def show; end

  # GET /slack_settings/new
  def new
    authorize :slack_setting, :new?

    @slack_setting = SlackSetting.new(project_id: params[:project_id])
  end

  # GET /slack_settings/1/edit
  def edit; end

  # POST /slack_settings
  # POST /slack_settings.json
  def create
    @slack_setting = SlackSetting.new(slack_setting_params)
    authorize @slack_setting
    respond_to do |format|
      if @slack_setting.save
        format.html { redirect_to projects_path, notice: 'Slack settings where successfully updated.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /slack_settings/1
  # PATCH/PUT /slack_settings/1.json
  def update
    respond_to do |format|
      if @slack_setting.update(slack_setting_params)
        format.html { redirect_to projects_path, notice: 'Slack settings where successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /slack_settings/1
  # DELETE /slack_settings/1.json
  def destroy
    @slack_setting.destroy
    respond_to do |format|
      format.html { redirect_to projects_path, notice: 'Slack notifications where successfully disabled.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_slack_setting
    @slack_setting = SlackSetting.find(params[:id])
    authorize @slack_setting
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def slack_setting_params
    params.require(:slack_setting).permit(:webhook_url, :channel, :username, :project_id)
  end
end

app/views/slack_settings/_form.html.erb
<%= form_for(slack_setting) do |f| %>
  <% if slack_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slack_setting.errors.count, "error") %> prohibited this slack_setting from being saved:</h2>

      <ul>
      <% slack_setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :webhook_url, class: 'form-label' %>
    <div class="control">
      <%= f.text_field :webhook_url, autofocus: true, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :channel, class: 'form-label' %>
    <div class="control">
      <%= f.text_field :channel, class: 'form-control' %>
    </div>
  </div>

  <div class="fieform-groupld">
    <%= f.label :username, class: 'form-label' %>
    <div class="control">
      <%= f.text_field :username, class: 'form-control' %>
    </div>
  </div>

  <%= f.hidden_field :project_id %>

  <div class="card-footer text-right">
    <%= f.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/slack_settings/edit.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="card-title"><%= @slack_setting.project.try(:name) %> - Slack Settings</h3>

    <div class="card-options">
      <%= link_to '<i class="fe fe-x"></i>'.html_safe, @slack_setting, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-options-remove' %>
    </div>
  </div>
  <div class="card-body">
    <%= render 'form', slack_setting: @slack_setting %>
  </div>
</div>

app/views/slack_settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slack Settings</h1>

<table>
  <thead>
    <tr>
      <th>Webhook url</th>
      <th>Channel</th>
      <th>Username</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slack_settings.each do |slack_setting| %>
      <tr>
        <td><%= slack_setting.webhook_url %></td>
        <td><%= slack_setting.channel %></td>
        <td><%= slack_setting.username %></td>
        <td><%= slack_setting.project %></td>
        <td><%= link_to 'Show', slack_setting %></td>
        <td><%= link_to 'Edit', edit_slack_setting_path(slack_setting) %></td>
        <td><%= link_to 'Destroy', slack_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slack Setting', new_slack_setting_path %>

app/views/slack_settings/new.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Slack Settings</h3>
  </div>
  <div class="card-body">
    <%= render 'form', slack_setting: @slack_setting %>
  </div>
</div>

app/views/slack_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Webhook url:</strong>
  <%= @slack_setting.webhook_url %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @slack_setting.channel %>
</p>

<p>
  <strong>Username:</strong>
  <%= @slack_setting.username %>
</p>

<p>
  <strong>Project:</strong>
  <%= @slack_setting.project %>
</p>

<%= link_to 'Edit', edit_slack_setting_path(@slack_setting) %> |
<%= link_to 'Back', slack_settings_path %>