config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'projects#index'
  devise_for :users, controllers: { invitations: 'users/invitations' }
  resources :users, only: %i[index show new create destroy update]
  resources :organisations, only: %i[index new create destroy]
  resources :sites, only: %i[show new create destroy] do
    get '/checks', to: 'sites#checks'
  end
  resources :projects, only: %i[index new create destroy]
  resources :slack_settings, only: %i[show new create update edit destroy]
  get '/probes', to: 'probes#index'
  post '/probes', to: 'probes#create'
  get '/probes/health/:id', to: 'probes#health'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  belongs_to :organisation
  validates :organisation, presence: true

  has_many :sites, dependent: :destroy
  has_one :slack_setting, dependent: :destroy
  validates :name, presence: true, uniqueness: { scope: :organisation }
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[show destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = policy_scope(Project)
  end

  # GET /projects/new
  def new
    authorize :project, :new?

    @project = Project.new
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    authorize @project

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    ModelDeleteJob.perform_later(@project)

    respond_to do |format|
      format.html { redirect_to projects_path, notice: 'Project was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
    authorize @project
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name).merge(organisation: current_user.organisation)
  end
end

app/views/projects/_form.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Creating Project</h3>
  </div>
  <div class="card-body">
    <%= form_for(project) do |f| %>
      <% if project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
          <% project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name, class: 'form-label' %>
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
      </div>

      <div class=" text-right">
        <%= f.submit "Save", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="my-3 my-md-5">
  <div class="container">
    <div class="row">
      <% @projects.each do |project| %>
      <div class="col-md-6 col-xl-4">
        <div class="card">
          <div class="card-status bg-green"></div>
          <div class="card-header">
            <h3 class="card-title"><%= project.name %></h3>
            <div class="card-options">
              <% if project.slack_setting %>
                <%= link_to '<i class="fe fe-slack"></i>'.html_safe, edit_slack_setting_path(project.slack_setting), class: 'slack_settings' %>
              <% else %>
                <%= link_to '<i class="fe fe-slack"></i>'.html_safe, new_slack_setting_path(project_id: project.id), class: 'slack_settings' %>
              <% end %>
              <%= link_to '<i class="fe fe-plus-circle"></i>'.html_safe, new_site_path(project: project.id), class: 'new_site' %>
            </div>
          </div>
          <table class="table card-table">
            <tbody>
              <% project.sites.each do |site| %>
                <tr>
                  <td><%= link_to site.name, site %></td>
                  <td class="text-right">
                    <span class="badge badge-<%= site_status_class(site) %>"><%= site.status.titlecase %></span>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <% end %>
      <div class="col-md-6 col-xl-4" style="text-align: center ">
        <div class="card" style="height: 200px">
          <%= link_to '<i class="fe fe-plus-circle" style="font-size: 30px;"></i>'.html_safe, new_project_path, style: 'margin-top: 80px; color: gray', id: 'new_project' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<%= render 'form', project: @project %>