config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'projects#index'
  devise_for :users, controllers: { invitations: 'users/invitations' }
  resources :users, only: %i[index show new create destroy update]
  resources :organisations, only: %i[index new create destroy]
  resources :sites, only: %i[show new create destroy] do
    get '/checks', to: 'sites#checks'
  end
  resources :projects, only: %i[index new create destroy]
  resources :slack_settings, only: %i[show new create update edit destroy]
  get '/probes', to: 'probes#index'
  post '/probes', to: 'probes#create'
  get '/probes/health/:id', to: 'probes#health'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/site.rb
# frozen_string_literal: true

class Site < ApplicationRecord
  include AASM

  belongs_to :project
  has_many :checks, dependent: :destroy
  after_commit :broadcast_change
  validates :name, presence: true, uniqueness: { scope: :project,
                                                 message: 'name must be unique' }

  validates :url, url: true, if: :http_check?
  validates :site_type, inclusion: { in: %w[http ping],
                                     message: '%{value} is not a valid site type' }
  validates :custom_status, numericality: { only_integer: true,
                                            greater_than_or_equal_to: 100,
                                            less_than_or_equal_to: 527 }, allow_nil: true

  aasm column: 'status' do
    state :unknown, initial: true
    state :active
    state :inactive

    event :success do
      transitions from: :unknown, to: :active
      transitions from: :active, to: :active
      transitions from: :inactive, to: :active, after: proc { |*_args| slack_notification }
    end

    event :fail do
      transitions from: :inactive, to: :inactive
      transitions from: :unknown, to: :inactive
      transitions from: :active, to: :inactive, after: proc { |*_args| slack_notification }
    end
  end

  def broadcast_change
    ActionCable.server.broadcast 'status',
                                 site: id,
                                 name: name,
                                 url: url,
                                 status: status
  end

  def uptime
    # Number of checks recieved
    total = checks.count

    # Number of inactive checks
    inactive = inactive_checks.count

    if total.zero?
      nil
    elsif inactive.zero?
      100
    else
      (100 - (inactive.to_f / total.to_f) * 100).round(2)
    end
  end

  def last_downtime
    inactive_checks.last.try(:created_at)
  end

  def inactive_checks
    if !http_check?
      checks.where.not(status: 1)
    elsif custom_status
      checks.where.not(status: custom_status)
    else
      checks.where('status < 199 OR status > 300')
    end
  end

  def slack_notification
    SlackNotificationJob.perform_later(self, checks.last.status)
  end

  def http_check?
    site_type == 'http'
  end
end

app/controllers/sites_controller.rb
# frozen_string_literal: true

class SitesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_site, only: %i[show checks destroy checks]

  # GET /sites/1
  # GET /sites/1.json
  def show; end

  # GET /sites/new
  def new
    authorize :site, :new?

    @site = Site.new(project_id: params[:project].to_i, site_type: params[:site_type].to_s)
  end

  # GET /sites/1/checks
  def checks
    render json: grouped_checks
  end

  # POST /sites
  # POST /sites.json
  def create
    # Concat protocol and url
    @site = Site.new(site_create_params)
    authorize @site

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    ModelDeleteJob.perform_later(@site)
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Site was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_site
    @site = Site.find(params[:id] || params[:site_id])
    authorize @site
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def site_params
    params.require(:site).permit(:name, :protocol, :url, :project_id, :verify_ssl, :custom_status, :basic_auth_username,
                                 :basic_auth_password, :site_type)
  end

  def site_create_params
    return site_params if site_params[:site_type] == 'ping'

    http_params(site_params)
  end

  def http_params(params)
    url = params[:protocol] && params[:url] ? params[:protocol] + params[:url] : nil
    params.merge(url: url).except(:protocol)
  end

  def grouped_checks
    Groupdate.time_zone = false

    @site.checks.group_by_period(
      chart_config['period'],
      :created_at,
      series: false,
      format: chart_config['format'],
      range: chart_config['range_from'].to_time(:utc)..Time.now.utc
    ).average(:time)
  end

  def chart_config
    Rails.application.config_for(:chart)[params[:range].nil? ? 'second' : params[:range]]
  end
end

app/views/sites/_choice.erb
<div class="row row-cards row-deck ">
    <div class=" col-md-3 offset-3">
        <a href="/sites/new?project=<%= @site.project_id %>&site_type=http" class="sites-create-choice-link">
            <div class="card sites-create-choice">
                <div class="card-body text-center">
                    HTTP
                    <br>
                    <span>Monitor the health of a service by sending periodic HTTP requests.<span>
                </div>
            </div>
        </a>
    </div>
    <div class="col-md-3">
        <a href="/sites/new?project=<%= @site.project_id %>&site_type=ping" class="sites-create-choice-link">
            <div class="card sites-create-choice">
                <div class="card-body text-center">
                    Ping
                    <br>
                    <span>Send periodic ICMP echo requests to a specific host.<span>
                </div>
            </div>
        </a>
    </div>
</div>

app/views/sites/_form_http.html.erb
<%= form_for(site) do |f| %>

  <div class="form-group">
    <label class="form-label">Name of Check<span class="form-required">*</span></label>
    <input type="text" class="form-control" name="site[name]" autofocus />
  </div>

  <ul class="nav nav-tabs">
    <li class="nav-item"><a class="nav-link active" data-tab="required">Required</a></li>
    <li class="nav-item"><a class="nav-link" data-tab="optional">Optional</a></li>
  </ul>

  <br>

  <div id="required" class="tab-content">

    <label class="form-label">URL<span class="form-required">*</span></label>

    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <div class="input-group-text">
          <select name="site[protocol]" class="btn btn-secondary dropdown-toggle" style="background: transparent; border: 0; box-shadow: none; -moz-appearance:none;appearance:none;">
            <option>https://</option>
            <option>http://</option>
          </select>
        </div>
      </div>
      <input class="form-control" type="text" name="site[url]">
    </div>

  </div>

  <div id="optional" class="tab-content hidden">

    <div class="form-group">
      <label class="form-label">Expected Status Code</label>
      <input class="form-control" type="number" min="1" max="65535" name="site[custom_status]">
    </div>

    <div class="form-group">
      <label class="form-label">Verify SSL</label>
      <label class="custom-switch">
        <input name="custom-switch-checkbox" class="custom-switch-input" type="checkbox" checked>
        <span class="custom-switch-indicator"></span>
        <span class="custom-switch-description">Yes</span>
      </label>
    </div>

    <div class="form-group">
      <label class="form-label">Basic Auth</label>

      <div class="row">
        <div class="col">
          <input class="form-control" type="text" placeholder="Username" name="site[basic_auth_username]">
        </div>
        <div class="col">
          <input class="form-control" type="text" placeholder="Password" name="site[basic_auth_password]">
        </div>
      </div>
    </div>

  </div>

  <%= f.hidden_field(:project_id, value: site.project_id) %>
  <%= f.hidden_field(:site_type, value: site.site_type) %>

  <br>

  <button type="submit" class="btn btn-primary">Save</button>
<% end %>

app/views/sites/_form_ping.html.erb
<%= form_for(site) do |f| %>

  <div class="form-group">
    <label class="form-label">Name of Check<span class="form-required">*</span></label>
    <input type="text" class="form-control" name="site[name]" autofocus />
  </div>


  <div id="required" class="tab-content">

    <label class="form-label">Hostname<span class="form-required">*</span></label>

    <div class="input-group mb-3">
      <input class="form-control" type="text" name="site[url]">
    </div>

  </div>


  <%= f.hidden_field(:project_id, value: site.project_id) %>
  <%= f.hidden_field(:site_type, value: site.site_type) %>


  <br>

  <button type="submit" class="btn btn-primary">Save</button>
<% end %>

app/views/sites/index.html.erb
<h1>Sites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Project</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.name %></td>
        <td><%= site.url %></td>
        <td><%= site.project %></td>
        <td><%= link_to 'Show', site %></td>
        <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Create Check</h3>
  </div>
  <div class="card-body">
    <% if params[:site_type] == 'http'%>
      <%= render 'form_http', site: @site %>
    <% elsif params[:site_type] == 'ping'%>
      <%= render 'form_ping', site: @site %>
    <% else %>
      <%= render 'choice' %>
    <% end %>
  </div>
</div>

app/views/sites/show.html.erb
<div class="card">
  <div class="card-body">
    <div class="float-right">
      <div class="control has-icons-left">
        <div class="select is-small">
          <select class="custom-select" id="chart-scope" data-id="<%= @site.id %>">
            <option selected value="second">1 hour</option>
            <option value="day">1 day</option>
            <option value="week">1 week</option>
            <option value="month">1 month</option>
          </select>
        </div>
      </div>
    </div>
    <h3 class="mb-1">
      <%= @site.name %>
    </h3>
    <div class="text-muted">
      <%= link_to @site, method: :delete do %>
        <small style="color: red"><i class="fe fe-x-circle" data-toggle="tooltip" title="Delete Site"></i></small>
      <% end %>
      <%= @site.site_type.titlecase %> - <%= @site.url %></div>
  </div>
  <div class="card-chart-bg" style="height: 320px">
    <%= line_chart site_checks_url(@site, { range: 'second' }), download: true %>
  </div>
</div>

<div class="row">
  <div class="col-sm-3">
    <div class="card">
      <div class="card-body text-center">
        <div class="h5">Uptime</div>
        <div class="display-4 font-weight-bold mb-4" style="font-size: 35px;">
          <%- if @site.checks.count > 0 %>
            <%= @site.uptime %>%
          <% else %>
            N/A
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="card">
      <div class="card-body text-center">
        <div class="h5">Average Response</div>
        <div class="display-4 font-weight-bold mb-4" style="font-size: 35px;">
          <%- if @site.checks.average(:time) %>
            <%= (@site.checks.average(:time) * 1000).round  %>ms
          <% else %>
            N/A
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="card">
      <div class="card-body text-center">
        <div class="h5">Last Downtime</div>
        <div class="display-4 font-weight-bold mb-4" style="font-size: 35px;">
            <%= timeago_tag @site.last_downtime, limit: nil, default: 'N/A' %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="card">
      <div class="card-body text-center">
        <div class="h5">Status</div>
        <div class="display-4 font-weight-bold mb-4" style="font-size: 35px;">
          <%= @site.status.titlecase %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-header">
    <h3 class="card-title">Latest Checks</h3>
  </div>
  <div class="table-responsive">
    <table class="table card-table table-striped table-vcenter">
      <thead>
        <tr>
          <th>Date/Time</th>
          <th>Response</th>
        </tr>
      </thead>
      <tbody>
        <% @site.checks.order('created_at desc').take(10).each do |check| %>
        <tr>
          <td><%= check.created_at.to_formatted_s(:custom_date) %></td>
          <td>
            <p class="tag <%= check_status_class(check) %>">
              <%= check.status ? check.status : 'Host Unreachable' if @site.site_type == 'http' %>
              <%= check.status == 1 ? 'Up' : 'Unreachable' if @site.site_type == 'ping' %>
            </p>
          </td>
        </tr>
        <% end %>
        <% if @site.checks.count > 10 %>
        <tr>
          <td colspan="3" class="text-center" style="color: gray">
            <%= @site.checks.count - 10 %> Previous Checks <br>
            <i class="fe fe-chevron-down"></i>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>